### ISSUE TITLE
Parameters to change for other FANUC robot

### ISSUE THREAD

**Issue by trydonot** [WuteYANG/FK-IK-for-FANUC-robot#1]
Hello,

I am trying to apply your code to FANUC R-2000iC/210F, but I am having some difficulties with which parameters I should change. Can you please help me with this? Which parameters should I change? Thank you

**Comment by WuteYANG** [comment]
That is the IK and FK for FANUC LR mate 200 id, so it is different from yours. You will need to change the DH-parameters. I have notes in the code, so you can find the DH parameters.
